services:
  postgres:
    image: postgres:16
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./services/init-db:/docker-entrypoint-initdb.d

  auth-service:
    build:
      context: ./services/auth/server
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      FIREBASE_CREDENTIAL: ${FIREBASE_CREDENTIAL}
    restart: unless-stopped

  data-service:
    build:
      context: ./services/data/server
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      FIREBASE_CREDENTIAL: ${FIREBASE_CREDENTIAL}
    restart: unless-stopped

  location-service:
    build:
      context: ./services/location/server
    ports:
      - "8083:8083"
    depends_on:
      - postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      FIREBASE_CREDENTIAL: ${FIREBASE_CREDENTIAL}
    restart: unless-stopped

  web-service:
    build:
      context: ./clients/web-app/frontend
    ports:
      - "5173:5173"
    depends_on:
      - auth-service
      - data-service
      - location-service
    environment:
      VITE_AUTH_URL: http://localhost:8081
      VITE_DATA_URL: http://localhost:8082
      VITE_LOCATION_URL: http://localhost:8083
    restart: unless-stopped

volumes:
  pgdata:
