version: "3.8"

services:
  postgres:
    image: postgres:16
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./services/init-db:/docker-entrypoint-initdb.d
    networks:
      - app-net

  auth-service:
    build:
      context: ./services/auth/server
    expose:
      - "8081"
    depends_on:
      - postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      FIREBASE_CREDENTIAL: ${FIREBASE_CREDENTIAL}
    restart: unless-stopped
    networks:
      - app-net

  data-service:
    build:
      context: ./services/data/server
    expose:
      - "8082"
    depends_on:
      - postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      FIREBASE_CREDENTIAL: ${FIREBASE_CREDENTIAL}
    restart: unless-stopped
    networks:
      - app-net

  location-service:
    build:
      context: ./services/location/server
    expose:
      - "8083"
    depends_on:
      - postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      FIREBASE_CREDENTIAL: ${FIREBASE_CREDENTIAL}
    restart: unless-stopped
    networks:
      - app-net

  web-service:
    build:
      context: ./clients/web-app/frontend
    expose:
      - "5173"
    depends_on:
      - auth-service
      - data-service
      - location-service
    environment:
      VITE_AUTH_URL: http://auth-service:8081
      VITE_DATA_URL: http://data-service:8082
      VITE_LOCATION_URL: http://location-service:8083
    restart: unless-stopped
    networks:
      - app-net

volumes:
  pgdata:

networks:
  app-net:
    driver: bridge
